version : '2'
networks:
  ridwands-network:

services:
  nginx:
      image: nginx:alpine
      ports:
        - "8082:80"
      volumes:
        - ./site.conf:/etc/nginx/conf.d/default.conf
      networks:
        - ridwands-network
  php:
      build:
        context: .
      volumes:
        - $PWD:/app
      networks:
        - ridwands-network

