version: '3.1'

networks:
  ridwands-network:
volumes:
  ridwands_volume_mongodb:
 
services:
  db:
    image: mongo:latest
    networks:
      - ridwands-network
    ports:
      - 27017:27017
    volumes:
      - ridwands_volume_mongodb
